# Generated by Django 5.1.2 on 2025-11-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling_system', '0012_exam_add_start_time_and_date_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvenue',
            name='is_core_exam',
        ),
    ]
