# Generated by Django 5.1.2 on 2025-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling_system', '0013_remove_examvenue_is_core_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date_exam',
        ),
        migrations.AddField(
            model_name='examvenue',
            name='core',
            field=models.BooleanField(default=False),
        ),
    ]
